### ISSUE TITLE
KITTI dataset split

### ISSUE THREAD

**Issue by PallottaEnrico** [XiYe20/STDiffProject#4]
Hello, congrats for you work! 
I wanted to ask how did you handled the KITTI dataset for training and testing.
Did you use left or right camera view? 
How did you split it in training and test?
How many test samples did you use for FVD calculation?

Thanks!
@XiYe20

**Comment by XiYe20** [comment]
Hi, Thanks for your interest in our work. For KITTI dataset, we follow the experiment setup of the paper "Learning Semantic-Aware Dynamics for Video Prediction", please refer to the  Datasets section of that paper. We download the raw data (synced+rectified) from KITTI official website. You may check the KITTIDataset() in stdiff/utils/dataset.py for the split of train/test set.  For every test example, we sample 10 different stochastic predictions (generated examples), then calculate the FVD score between all generated examples and ground-truth examples.

**Comment by KELISBU** [comment]
Good job！ 
I am wondering how you calculate FVD for the predicted 5 frames on KITTI dataset?
